server:
  port: 8082

spring:
  cloud:
    function:
      definition: userConsumer

    stream:
      bindings:
        userConsumer-in-0:
          destination: users-v1
      kafka:
        binder:
          brokers: localhost:9092
  integration:
    poller:
      fixed-delay: 5000
  datasource:
    url: jdbc:h2:mem:usersdb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true